### ISSUE TITLE
Allow ability to pass in --no-configuration-cache argument

### ISSUE THREAD

**Issue by mhernand40** [usefulness/dependency-tree-diff-action#43]
I'm working out of a project that enables configuration cache by default for the entire project. However, the `dependencies` currently does not work well with configuration cache.

Please see:
* https://github.com/gradle/gradle/issues/17470

Whenever I try using this GitHub action in my project, I get the following failure in CI:
```
* What went wrong:
Execution failed for task ':app:dependencies'.
> The value of this property has been discarded during serialization.
```

I guess we could wait until Gradle `7.6.0` gets officially released but in the meantime, it would be great if we could pass in additional optional arguments to the `dependencies` task so that I can pass in `--no-configuration-cache` until this issue gets resolved by Gradle.

**Comment by mateuszkwiecinski** [comment]
Hey 👋  Thanks for the report! 
I added new argument `additional-gradle-arguments` which will be passed to each Gradle invocation. In your case, passing a `additional-gradle-arguments: "--no-configuration-cache"` should do the trick (but please make sure you're using the latest version `1.1.3`)

**Comment by mhernand40** [comment]
Thank you @mateuszkwiecinski. Works like a charm 👍
